//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace el_amaniBackoffice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrashPrice
    {
        public int id { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string messag { get; set; }
        public string url_image_1 { get; set; }
        public string url_image_2 { get; set; }
        public string url_image_3 { get; set; }
        public Nullable<bool> statuss { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
    }
}
